/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_wouterdek_jrenderdoc_RenderDoc_Natives */

#ifndef _Included_com_github_wouterdek_jrenderdoc_RenderDoc_Natives
#define _Included_com_github_wouterdek_jrenderdoc_RenderDoc_Natives
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_isAttached
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1isAttached
  (JNIEnv *, jobject);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_getApi
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1getApi
  (JNIEnv *, jobject);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_getAPIVersion
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1getAPIVersion
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_setCaptureOptionU32
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1setCaptureOptionU32
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_setCaptureOptionF32
 * Signature: (JIF)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1setCaptureOptionF32
  (JNIEnv *, jobject, jlong, jint, jfloat);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_getCaptureOptionU32
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1getCaptureOptionU32
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_getCaptureOptionF32
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1getCaptureOptionF32
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_setFocusToggleKeys
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1setFocusToggleKeys
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_setCaptureKeys
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1setCaptureKeys
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_getOverlayBits
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1getOverlayBits
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_maskOverlayBits
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1maskOverlayBits
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_shutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1shutdown
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_unloadCrashHandler
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1unloadCrashHandler
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_setCaptureFilePathTemplate
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1setCaptureFilePathTemplate
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_getCaptureFilePathTemplate
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1getCaptureFilePathTemplate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_getNumCaptures
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1getNumCaptures
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_getCapture
 * Signature: (JI)Lcom/github/wouterdek/jrenderdoc/Capture;
 */
JNIEXPORT jobject JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1getCapture
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_triggerCapture
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1triggerCapture
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_isTargetControlConnected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1isTargetControlConnected
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_launchReplayUI
 * Signature: (JZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1launchReplayUI
  (JNIEnv *, jobject, jlong, jboolean, jstring);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_setActiveWindow
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1setActiveWindow
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_startFrameCapture
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1startFrameCapture
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_isFrameCapturing
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1isFrameCapturing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_endFrameCapture
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1endFrameCapture
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     com_github_wouterdek_jrenderdoc_RenderDoc_Natives
 * Method:    n_triggerMultiFrameCapture
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_github_wouterdek_jrenderdoc_RenderDoc_00024Natives_n_1triggerMultiFrameCapture
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
